version: '3.5'

x-app: &base-app
  build:
    context: .
    target: app
  depends_on:
    - database
  volumes:
    - ./src:/app/src
    - ./tests:/app/tests
    - ./deploy:/app/deploy
  environment: &base-app-env
    SECRET_KEY: "insecure"
    DEBUG: "true"
    AUTHORIZATION_TOKEN: "dev"
    PYTHONBREAKPOINT:
    DJANGO_LOG_LEVEL:
    JANITOR_LOG_LEVEL:
  entrypoint: /app/deploy/wait-for-it.sh database:5432 --
  
volumes:
  db_data:
  db_wal:

services:
  database:
    image: timescale/timescaledb-postgis:1.4.2-pg11
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
      POSTGRES_INITDB_WALDIR: /wal
    volumes:
      - db_data:/data
      - db_wal:/wal

  dev:
    <<: *base-app
    build:
      context: .
      target: dev
    command: python manage.py runserver_plus 0.0.0.0:8000

  app:
    <<: *base-app
    build:
      context: .
      target: app
      args:
        - BUILD_DATE
        - BUILD_REVISION
        - BUILD_VERSION
    image: docker-registry.data.amsterdam.nl/datapunt/waarnemingen-voertuigen:${VERSION:-latest}
    command: /app/deploy/docker-run.sh

  test:
    <<: *base-app
    build:
      context: .
      target: tests
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "main.settings"
      PYTEST_ADDOPTS:
